language: python
python:
  - "2.7"

script:
  - python program.py

virtualenv:
  system_site_packages: true

notifications:
   slack: epsiic:ktzjhF2hKb3rR8f9gSXYf0Hm

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "epicmess-github" 
    
            
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner -X

