language: python
python:
  - "2.7"
# command to install dependencies
#install:
 # - pip install -r requirements.txt
# command to run tests
script:
  - python program.py

virtualenv:
  system_site_packages: true

 notifications:
    slack: epsiic:ktzjhF2hKb3rR8f9gSXYf0Hm
